"""The one new LLM call this feature adds: an advisory read of the three
deterministic engines' already-computed output plus the proposed signal.

Interprets evidence, never replaces it — every number in the prompt comes
from dcf_result/technical_result/sentiment_score/proposed_signal exactly
as the deterministic engines and evaluate_entry produced them. This module
does no math of its own.
"""
import os

from anthropic import Anthropic

from engine.llm_json import call_and_extract_json

MODEL = "claude-sonnet-5"
MAX_TOKENS = 1500

_client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

PROMPT_TEMPLATE = """You are reviewing a candidate stock trade that was already
generated by deterministic rules. You are not deciding whether to trade —
that decision has already been made by code. Your job is only to interpret
the evidence below and flag anything a human reviewer should know before
approving it.

Ticker: {ticker}

Valuation (DCF):
{dcf_result}

Technical analysis:
{technical_result}

News sentiment (24h average, -1 bearish to 1 bullish): {sentiment_score}

Proposed signal (already decided by rule-based code, NOT by you):
{proposed_signal}
{feedback_section}
Respond with a brief written assessment, then end your response with EXACTLY
this JSON block and nothing after it:
{{
  "agreement": true or false (does the evidence above support this trade?),
  "confidence": 0-100,
  "reasoning": "one or two sentences",
  "notable_risks": ["short risk phrase", "..."],
  "cited_fair_value": <the exact fair value number from the DCF above, or null>,
  "cited_entry_price": <the exact entry price number from the technicals above, or null>
}}"""


def run_llm_synthesis(
    ticker: str,
    dcf_result: dict,
    technical_result: dict,
    sentiment_score: float,
    proposed_signal: dict,
    prior_errors: list[str] | None = None,
) -> dict:
    """Returns {"raw_output": str, "structured": dict}, same shape as the
    other engine LLM calls (run_dcf, run_technical_scan)."""
    feedback_section = ""
    if prior_errors:
        feedback_section = (
            "\nYour previous response failed validation for these reasons:\n"
            + "\n".join(f"- {err}" for err in prior_errors)
            + "\nFix these specifically in your next response.\n"
        )
    prompt = PROMPT_TEMPLATE.format(
        ticker=ticker,
        dcf_result=dcf_result,
        technical_result=technical_result,
        sentiment_score=sentiment_score,
        proposed_signal=proposed_signal,
        feedback_section=feedback_section,
    )
    raw_output, structured = call_and_extract_json(_client, MODEL, prompt, MAX_TOKENS)
    return {"raw_output": raw_output, "structured": structured}
